controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

json.test:
    resource: ../src/B2b/Json/Infrastructure/Routes/test.yml
json.reward:
    resource: ../src/B2b/Json/Infrastructure/Routes/reward.yml